## **Import Libraries & Load Data**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Load dataset
df = pd.read_csv('/content/drive/My Drive/Customer_behaviours/Datasets/ecommerce_customer_data_large.csv')

In [4]:
# Preview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  object
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                202618 non-null  float64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB

In [5]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,31,1.0,John Rivera,31,Female,0
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,31,1.0,John Rivera,31,Female,0
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,31,1.0,John Rivera,31,Female,0
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,31,0.0,John Rivera,31,Female,0
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,31,1.0,John Rivera,31,Female,0

## **Standardize Column Names**

In [6]:
df.columns

Index(['Customer ID', 'Purchase Date', 'Product Category', 'Product Price',
       'Quantity', 'Total Purchase Amount', 'Payment Method', 'Customer Age',
       'Returns', 'Customer Name', 'Age', 'Gender', 'Churn'],
      dtype='object')

In [7]:
df.columns= df.columns.str.strip().str.lower().str.replace(' ', '_')

In [8]:
df.columns

Index(['customer_id', 'purchase_date', 'product_category', 'product_price',
       'quantity', 'total_purchase_amount', 'payment_method', 'customer_age',
       'returns', 'customer_name', 'age', 'gender', 'churn'],
      dtype='object')

## **Handle Duplicate Columns**

In [9]:
df = df.drop(columns=['customer_age'])

In [10]:
df.columns

Index(['customer_id', 'purchase_date', 'product_category', 'product_price',
       'quantity', 'total_purchase_amount', 'payment_method', 'returns',
       'customer_name', 'age', 'gender', 'churn'],
      dtype='object')

## **Fix Date Column**

In [11]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

In [12]:
df['purchase_date'].isnull().sum()

np.int64(0)

## **Handle Missing Values**

In [13]:
df.isnull().sum()

customer_id                  0
purchase_date                0
product_category             0
product_price                0
quantity                     0
total_purchase_amount        0
payment_method               0
returns                  47382
customer_name                0
age                          0
gender                       0
churn                        0
dtype: int64

**Fix important columns:**

In [14]:
#Returns → fill with 0
df['returns'] = df['returns'].fillna(0)

In [15]:
df.isnull().sum()

customer_id              0
purchase_date            0
product_category         0
product_price            0
quantity                 0
total_purchase_amount    0
payment_method           0
returns                  0
customer_name            0
age                      0
gender                   0
churn                    0
dtype: int64

## **Remove Duplicates**

In [16]:
df.duplicated().sum()

np.int64(0)

## **Fix Data Types**

In [17]:
df['product_price'] = pd.to_numeric(df['product_price'], errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['total_purchase_amount'] = pd.to_numeric(df['total_purchase_amount'], errors='coerce')
df['age'] = pd.to_numeric(df['age'], errors='coerce')

## **Clean Categorical Data**

In [18]:
df['product_category'] = df['product_category'].str.strip()
df['payment_method'] = df['payment_method'].str.strip()
df['gender'] = df['gender'].str.strip().str.capitalize()

## **Create Useful Features**

In [19]:
df['year'] = df['purchase_date'].dt.year
df['month'] = df['purchase_date'].dt.month_name()
df['day'] = df['purchase_date'].dt.day_name()

In [20]:
df['month']

0               May
1               May
2              July
3           January
4               May
            ...
249995      January
249996         June
249997     November
249998         June
249999    September
Name: month, Length: 250000, dtype: object

In [21]:
df['day']

0         Wednesday
1            Sunday
2            Monday
3           Tuesday
4          Saturday
            ...
249995      Tuesday
249996       Friday
249997     Thursday
249998       Sunday
249999       Monday
Name: day, Length: 250000, dtype: object

## **Final Check**

In [22]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            250000 non-null  int64
 1   purchase_date          250000 non-null  datetime64[ns]
 2   product_category       250000 non-null  object
 3   product_price          250000 non-null  int64
 4   quantity               250000 non-null  int64
 5   total_purchase_amount  250000 non-null  int64
 6   payment_method         250000 non-null  object
 7   returns                250000 non-null  float64
 8   customer_name          250000 non-null  object
 9   age                    250000 non-null  int64
 10  gender                 250000 non-null  object
 11  churn                  250000 non-null  int64
 12  year                   250000 non-null  int32
 13  month                  250000 non-null  object
 14  day                    250000 non-null  object
dtypes: datetime64[ns](1), float64(1), int32(1), int64(6), object(6)
memory usage: 27.7+ MB

,customer_id,purchase_date,product_category,product_price,quantity,total_purchase_amount,payment_method,returns,customer_name,age,gender,churn,year,month,day
0,44605,2023-05-03 21:30:02,Home,177,1,2427,PayPal,1.0,John Rivera,31,Female,0,2023,May,Wednesday
1,44605,2021-05-16 13:57:44,Electronics,174,3,2448,PayPal,1.0,John Rivera,31,Female,0,2021,May,Sunday
2,44605,2020-07-13 06:16:57,Books,413,1,2345,Credit Card,1.0,John Rivera,31,Female,0,2020,July,Monday
3,44605,2023-01-17 13:14:36,Electronics,396,3,937,Cash,0.0,John Rivera,31,Female,0,2023,January,Tuesday
4,44605,2021-05-01 11:29:27,Books,259,4,2598,PayPal,1.0,John Rivera,31,Female,0,2021,May,Saturday

## **Save Clean Dataset**

In [23]:
df.to_csv('/content/drive/My Drive/Customer_behaviours/Datasets/ecommerce_customer_data_large_cleaned.csv', index=False)